/**
 * components/AlertCard/AlertCard.jsx
 * Expandable alert card generated by the AI engine.
 * Shows severity, title, probability and evidence artifacts.
 */
import React, { useState } from 'react';
import './AlertCard.css';

const IconPR     = () => <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><circle cx="3" cy="3" r="1.5" stroke="currentColor" strokeWidth="1.2"/><circle cx="3" cy="9" r="1.5" stroke="currentColor" strokeWidth="1.2"/><circle cx="9" cy="3" r="1.5" stroke="currentColor" strokeWidth="1.2"/><path d="M3 4.5v3" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><path d="M9 4.5a2 2 0 0 1-2 2H5.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></svg>;
const IconCommit = () => <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><circle cx="6" cy="6" r="2" stroke="currentColor" strokeWidth="1.2"/><line x1="0" y1="6" x2="4" y2="6" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><line x1="8" y1="6" x2="12" y2="6" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></svg>;
const IconIssue  = () => <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><circle cx="6" cy="6" r="4.5" stroke="currentColor" strokeWidth="1.2"/><line x1="6" y1="4" x2="6" y2="6.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><circle cx="6" cy="8.5" r="0.6" fill="currentColor"/></svg>;
const IconChevron = ({ open }) => (
  <svg width="13" height="13" viewBox="0 0 13 13" fill="none"
    style={{ transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 200ms ease', flexShrink: 0 }}>
    <path d="M3 5l3.5 3.5L10 5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

const EVIDENCE_ICONS = { pr: IconPR, commit: IconCommit, issue: IconIssue };

const SEVERITY_CONFIG = {
  critical: { label: 'Crítico',  colorVar: '--color-risk-critical',  bgVar: '--color-risk-critical-bg'  },
  warning:  { label: 'Atenção',  colorVar: '--color-risk-warning',   bgVar: '--color-risk-warning-bg'   },
  info:     { label: 'Info',     colorVar: '--color-status-info',    bgVar: '--color-status-info-bg'    },
};

function AlertCard({ severity = 'warning', title, probability, description, evidence = [], timestamp }) {
  const [open, setOpen] = useState(false);
  const config = SEVERITY_CONFIG[severity] ?? SEVERITY_CONFIG.warning;

  return (
    <div
      className={`alert-card alert-card--${severity}`}
      style={{ '--alert-color': `var(${config.colorVar})`, '--alert-bg': `var(${config.bgVar})` }}
    >
      {/* Header — always visible */}
      <button
        className="alert-card__header"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        aria-controls={`alert-body-${title}`}
      >
        <span className="alert-card__severity-badge">
          <span className="alert-card__severity-dot" aria-hidden="true" />
          {config.label}
        </span>

        <span className="alert-card__title">{title}</span>

        {probability != null && (
          <span className="alert-card__probability" aria-label={`Probabilidade: ${probability}%`}>
            {probability}%
          </span>
        )}

        <IconChevron open={open} />
      </button>

      {/* Body — expandable */}
      {open && (
        <div className="alert-card__body" id={`alert-body-${title}`} role="region">
          {description && (
            <p className="alert-card__description">{description}</p>
          )}

          {evidence.length > 0 && (
            <div className="alert-card__evidence">
              <span className="alert-card__evidence-label">Evidências</span>
              <ul className="alert-card__evidence-list">
                {evidence.map((ev, i) => {
                  const Icon = EVIDENCE_ICONS[ev.type] ?? IconIssue;
                  return (
                    <li key={i} className="alert-card__evidence-item">
                      <span className="alert-card__evidence-icon" aria-hidden="true"><Icon /></span>
                      <a
                        href={ev.url ?? '#'}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="alert-card__evidence-id"
                      >
                        {ev.id}
                      </a>
                      <span className="alert-card__evidence-excerpt">{ev.excerpt}</span>
                    </li>
                  );
                })}
              </ul>
            </div>
          )}

          {timestamp && (
            <span className="alert-card__timestamp">
              Gerado em {timestamp}
            </span>
          )}
        </div>
      )}
    </div>
  );
}

export default AlertCard;
